name: Sync tagmark-ui

on:
  repository_dispatch:
    types:
      - tagmark-ui-main-update
  push:
    paths:
      - 'data/*'
      - 'docs/'

  workflow_dispatch:

env:
  TAGMARK_UI_DIR: tagmark-ui

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Update TagMark UI
    steps:
    - name: Checkout This Repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_PAT_TAGMARK }}

    - name: Checkout and Merge tagmark-ui Code
      uses: actions/checkout@v3
      with:
        repository: pwnfan/tagmark-ui
        path: ${{ env.TAGMARK_UI_DIR }}
        ref: main
  
    - name: Merge New tagmark-ui code
      run: |
        rm -rf \
          ${{ env.TAGMARK_UI_DIR }}/.git* \
          ${{ env.TAGMARK_UI_DIR }}/*.md \
          ${{ env.TAGMARK_UI_DIR }}/LICENSE \
          ${{ env.TAGMARK_UI_DIR }}/Makefile \
          ${{ env.TAGMARK_UI_DIR }}/data/ \
          ${{ env.TAGMARK_UI_DIR }}/docs/tag-doc.*
        cp -rf ${{ env.TAGMARK_UI_DIR }}/* ./
        rm -rf ${{ env.TAGMARK_UI_DIR }}
    
    - name: Commit and Push New Code
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        pull: '--autostash'
